apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      initContainers:
        - name: wait-for-event-bus
          image: busybox
          command:
            [
              'sh',
              '-c',
              'until nc -z event-bus-srv 4005; do echo waiting for event-bus; sleep 2; done',
            ]
      containers:
        - name: query
          image: anthonynaui/query
---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  selector:
    app: query
  ports:
    - name: query
      protocol: TCP
      port: 4002
      targetPort: 4002
